#!/bin/sh

# Load X settings
xrdb -load $HOME/.Xdefaults

# Override bad enter
setxkbmap us
xmodmap .xmodmap

# Initiate dual screen layout
xrandr --output DVI-I-3 --mode 1920x1080 --pos 0x0 --rotate left --output DVI-I-2 --mode 1920x1080 --pos 1080x480

# Set backgrounds
nitrogen --restore

# Set mouse pointer
xsetroot -cursor_name left_ptr

# Startup skyped
#skyped

# Start xmonad yay!
exec xmonad

