#!/bin/sh

# Load X settings
xrdb -load $HOME/.Xdefaults

# Override bad enter
#setxkbmap us
#xmodmap .xmodmap

# Set backgrounds
nitrogen --restore

# Set mouse pointer
xsetroot -cursor_name left_ptr

# Startup skyped
# skyped

# Start xmonad yay!
exec xmonad

