-- Table handling
-- 1. Move between table cell (text objects)
-- 1. Edit table cell (text object)
--
-- Links
-- 1. Convert inline_link to collapsed reference link
-- 1. Rewrite all reference link labels (of either link def or at the link itself)
--
-- Lists
-- 1. Update task list markers above
-- 1. Quick way to add a task link (or add a new list item, at the end of current list)
--    (On enter in insert mode, or o or O?)
--
-- Headings
-- 1. Raise/lower heading levels on cursor/selection
-- 1. Rewrite jump to next heading (and jump between sections)
--
-- Format on save
-- + Format table
-- + Spacing before sections
-- + Reorder lists
-- (configurable)
-- + Fix code block indents
-- + Could we format code inside the code blocks too?
--
-- Textobjects:
-- Prev/Next heading
-- Prev/Next section
-- Left/Right/Above/Below table cells
-- Current table cell
-- Attributes?
