# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1296336097);
user_pref("app.update.lastUpdateTime.background-update-timer", 1296336097);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1296336097);
user_pref("extensions.enabledItems", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.4");
user_pref("extensions.lastAppVersion", "3.0.4");
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.smtpservers", "");
user_pref("mailnews.quotingPrefs.version", 1);
