-- FIXME isn't registering...?
-- require("lint").linters_by_ft = {
--   elixir = { "credo" },
-- }
--
-- vim.api.nvim_create_autocmd({ "BufWritePost" }, {
--   callback = function()
--     require("lint").try_lint()
--   end,
-- })
