[plugins]
"rocks.nvim" = "2.31.0"
"rocks-config.nvim" = "1.6.0"
"rocks-git.nvim" = "1.5.1"
"rocks-dev.nvim" = "1.2.3"
"melange-nvim" = { git = "savq/melange-nvim" }
"mini.cursorword" = "0.9.0"
"mini.trailspace" = "0.9.0"
"mini.ai" = "0.9.0"
"conform.nvim" = "5.9.0"
"neo-tree.nvim" = "3.26"
"telescope.nvim" = "scm"
"comment.nvim" = "0.8.0"
"indent-blankline.nvim" = "3.6.2"
"oil.nvim" = "2.9.0"
"todo-comments.nvim" = "1.2.0"
"vim-cool" = { git = "romainl/vim-cool" }
"vim-sleuth" = { git = "tpope/vim-sleuth" }
"suda.vim" = { git = "lambdalisue/vim-suda" }
"replacer.nvim" = { git = "gabrielpoca/replacer.nvim" }
"zoxide.vim" = { git = "nanotee/zoxide.vim" }
nvim-web-devicons = "0.100"
"lualine.nvim" = "scm"
"lsp-status.nvim" = "scm"
"elixir-tools.nvim" = "0.14.3"
"nerdy.nvim" = { git = "2kabhishek/nerdy.nvim" }
"search-replace.nvim" = { git = "roobert/search-replace.nvim" }
"marks.nvim" = "scm"
"vim-fugitive" = { git = "tpope/vim-fugitive" }
neogit = { git = "TimUntersberger/neogit" }
nvim-nio = "1.9.4"
nvim-lastplace = "1.0.0"
vim-matchup = { git = "andymass/vim-matchup" }
vim-maximizer = { git = "szw/vim-maximizer" }
alpha-nvim = "scm"
nvim-cmp = "scm"
undotree = { git = "jiaoshijie/undotree" }
"lspkind.nvim" = "scm"
cmp-nvim-lsp = "scm"
cmp-buffer = "scm"
cmp-cmdline = "scm"
cmp-async-path = { git = "https://codeberg.org/FelipeLema/cmp-async-path.git" }
cmp-spell = { git = "f3fora/cmp-spell" }
cmp-calc = { git = "hrsh7th/cmp-calc" }
cmp-nvim-lua = { git = "hrsh7th/cmp-nvim-lua" }
cmp-treesitter = { git = "ray-x/cmp-treesitter" }
nvim-treesitter = { git = "nvim-treesitter/nvim-treesitter" }
nvim-treesitter-endwise = { git = "RRethy/nvim-treesitter-endwise" }
nvim-ts-context-commentstring = { git = "JoosepAlviste/nvim-ts-context-commentstring" }
nvim-treesitter-context = { git = "nvim-treesitter/nvim-treesitter-context" }
nvim-ts-autotag = { git = "windwp/nvim-ts-autotag" }
nvim-treesitter-textobjects = { git = "nvim-treesitter/nvim-treesitter-textobjects" }
vim-pollen = { git = "otherjoel/vim-pollen" }
"gitsigns.nvim" = { git = "lewis6991/gitsigns.nvim" }
"dial.nvim" = { git = "monaqa/dial.nvim" }
"telescope-fzf-native.nvim" = { git = "nvim-telescope/telescope-fzf-native.nvim", build = "make" }
"mason.nvim" = { version = "1.10.0" }
"mason-lspconfig.nvim" = { version = "1.29.0" }
nvim-lspconfig = "0.1.8"
rustaceanvim = "4.25.0"
"typescript-tools.nvim" = "scm"
"tardis.nvim" = { git = "fredeeb/tardis.nvim" }
"blame.nvim" = { git = "FabijanZulj/blame.nvim" }
"nvim-highlight-colors" = { git = "brenoprata10/nvim-highlight-colors"}
"vim-dadbod" = { git = "tpope/vim-dadbod" }
"vim-dadbod-completion" = { git = "kristijanhusak/vim-dadbod-completion" }
"vim-dadbod-ui" = { git = "kristijanhusak/vim-dadbod-ui" }
"project.nvim" = "scm"
"trouble.nvim" = "3.4.2"
"lazydev.nvim" = { git = "folke/lazydev.nvim" }
"hurl.nvim" = { git = "jellydn/hurl.nvim" }
# neotest = "scm"
neotest = { git = "nvim-neotest/neotest"}
"neotest-elixir" = { git = "jfpedroza/neotest-elixir" }
"neotest-vim-test" = { git = "nvim-neotest/neotest-vim-test" }
"vim-test" = { git = "vim-test/vim-test" }
nvim-lint = "scm"

# "neotest-gleam" = { dir = "~/code/neotest-gleam" }
