local cmd = require("util.helpers").create_cmd

cmd("BlogStart", function()
  require("blog.server").start()
end)
cmd("BlogStop", function()
  require("blog.server").stop()
end)
cmd("BlogRestart", function()
  require("blog.server").restart()
end)
cmd("BlogReconnect", function()
  require("blog.server").reconnect()
end)

cmd("BlogNewDraft", function()
  require("blog.files").new_draft()
end)
cmd("BlogNewSeries", function()
  require("blog.files").new_series()
end)
cmd("BlogNewStatic", function()
  require("blog.files").new_static()
end)
cmd("BlogNewProject", function()
  require("blog.files").new_project()
end)

cmd("BlogPromoteDraft", function()
  require("blog.files").promote_curr_draft()
end)
cmd("BlogDemotePost", function()
  require("blog.files").demote_curr_post()
end)

cmd("BlogPreview", function()
  require("blog.files").open_curr_post_in_browser()
end)

-- cmd("BlogInfo", server.info)
